# Generated by Django 3.2.3 on 2022-03-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20220317_0701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iot',
            table='Logging',
        ),
    ]
