# Generated by Django 3.2.3 on 2022-03-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20220323_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'Aktif'), (False, 'Tidak Aktif')], default=True),
        ),
    ]
