# Generated by Django 3.2.3 on 2022-03-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_department_report_reporttitle_uploadedregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedregister',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='mainApp.product'),
            preserve_default=False,
        ),
    ]
