# Generated by Django 3.1.6 on 2022-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20220331_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maxweight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='minweight',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
    ]
