# Generated by Django 3.2.3 on 2022-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20220415_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstate',
            name='status',
            field=models.BooleanField(choices=[(True, 'Aktif'), (False, 'Tidak Aktif')], default=True),
        ),
    ]
