# Generated by Django 3.2.3 on 2022-04-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_productstate_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductState',
            new_name='WeighingState',
        ),
    ]
