# Generated by Django 3.2.3 on 2022-04-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_rename_productstate_weighingstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
