# Generated by Django 3.2.3 on 2022-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingstate',
            name='batchno',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
