# Generated by Django 3.2.3 on 2022-04-19 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0015_weighingstate_batchno'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='createdby', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updatedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
