# Generated by Django 3.1.6 on 2022-04-20 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0016_auto_20220419_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='createdby_rel', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updatedby_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
