# Generated by Django 3.1.6 on 2022-04-20 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0017_auto_20220420_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingstate',
            name='spvgudang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='spvgudang', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weighingstate',
            name='spvpabrik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='spvpabrik', to='auth.user'),
            preserve_default=False,
        ),
    ]
