# Generated by Django 3.2.3 on 2022-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_weighingstate_pendingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingstate',
            name='pendingstatus',
            field=models.BooleanField(choices=[(1, 'Pending'), (0, 'Close')], default=True),
        ),
    ]
