# Generated by Django 3.2.3 on 2022-05-18 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0020_alter_weighingstate_pendingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingstate',
            name='spvgudang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='spvgudang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weighingstate',
            name='spvpabrik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='spvpabrik', to=settings.AUTH_USER_MODEL),
        ),
    ]
