# Generated by Django 3.2.3 on 2022-06-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_auto_20220521_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
