# Generated by Django 3.2.3 on 2022-06-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_alter_register_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
