# Generated by Django 3.1.6 on 2022-06-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_alter_register_weight'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='register',
            name='productBatchnoBoxno',
        ),
        migrations.RemoveField(
            model_name='register',
            name='product',
        ),
    ]
