# Generated by Django 3.2.3 on 2022-06-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_alter_register_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='product',
        ),
    ]
