# Generated by Django 3.2.3 on 2022-06-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_remove_register_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='register',
            name='productBatchnoBoxno',
        ),
    ]
