# Generated by Django 3.2.3 on 2022-06-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_remove_register_productbatchnoboxno'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='product',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.RESTRICT, to='mainApp.product'),
            preserve_default=False,
        ),
    ]
