# Generated by Django 3.2.3 on 2022-06-16 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0027_register_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingstate',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weighingstate',
            name='petugasgudang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='petugasgudang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReportRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnrev', models.IntegerField()),
                ('batchno', models.CharField(max_length=15)),
                ('boxno', models.IntegerField()),
                ('status', models.IntegerField(default=None, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainApp.product')),
            ],
        ),
    ]
