# Generated by Django 3.1.6 on 2022-07-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0028_auto_20220616_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('minweight', models.FloatField()),
                ('maxweight', models.FloatField()),
                ('standardweight', models.FloatField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(True, 'Aktif'), (False, 'Tidak Aktif')], default=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='createdbyhistory', to=settings.AUTH_USER_MODEL)),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updatedbyhistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
