# Generated by Django 3.2.3 on 2022-07-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_productuploadtemp_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportregister',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='mainApp.report'),
            preserve_default=False,
        ),
    ]
