# Generated by Django 3.1.6 on 2022-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_reportregister_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingstate',
            name='weightadjustment',
            field=models.FloatField(default=0),
        ),
    ]
