# Generated by Django 3.2.3 on 2022-08-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_auto_20220808_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spvinterrupt', models.BooleanField(default=False)),
                ('spvinterruptexpireddate', models.DateTimeField(blank=True, default=None, null=True)),
                ('weightadjustment', models.FloatField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainApp.department')),
                ('reporttitle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainApp.reporttitle')),
            ],
        ),
    ]
