# Generated by Django 3.2.3 on 2022-08-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_adminconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminconfig',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainApp.department'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='reporttitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainApp.reporttitle'),
        ),
    ]
