# Generated by Django 3.2.3 on 2022-08-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_auto_20220808_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminconfig',
            old_name='spvinterrupt',
            new_name='spvapproval',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='spvinterruptexpireddate',
            new_name='spvapprovalexpireddate',
        ),
    ]
