# Generated by Django 3.2.3 on 2022-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_auto_20220808_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='jumlahkoli',
            field=models.IntegerField(default=0),
        ),
    ]
