# Generated by Django 3.2.3 on 2022-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_producthistory_jumlahkoli'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploadtemp',
            name='jumlahkoli',
            field=models.IntegerField(default=0),
        ),
    ]
