# Generated by Django 3.2.3 on 2022-08-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_productuploadtemp_jumlahkoli'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='operator1',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='operator2',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
