# Generated by Django 3.2.3 on 2022-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_auto_20220809_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='operator1',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='operator2',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
