# Generated by Django 3.2.3 on 2022-08-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0042_auto_20220809_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportregister',
            name='operator1',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportregister',
            name='operator2',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
