# Generated by Django 3.2.3 on 2022-08-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_auto_20220810_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='operator1',
            new_name='operator',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='operator2',
            new_name='petugasgudang',
        ),
        migrations.RenameField(
            model_name='reportregister',
            old_name='operator1',
            new_name='operator',
        ),
        migrations.RenameField(
            model_name='reportregister',
            old_name='operator2',
            new_name='petugasgudang',
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='operator1',
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='operator2',
        ),
    ]
