# Generated by Django 3.2.3 on 2022-08-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0044_auto_20220810_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingstate',
            name='petugasgudang',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
