# Generated by Django 3.2.3 on 2022-08-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0047_alter_weighingstate_expireddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='operator',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='petugasgudang',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weighingstate',
            name='expireddate',
            field=models.CharField(max_length=20),
        ),
    ]
