# Generated by Django 3.2.3 on 2022-08-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0048_auto_20220819_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportregister',
            name='createdon',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reportregister',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.report'),
        ),
    ]
