# Generated by Django 3.1.6 on 2022-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0049_auto_20220830_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='dilakukan_oleh',
            field=models.CharField(default='Dilakukan oleh', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='diperiksa_oleh',
            field=models.CharField(default='Diperiksa oleh', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='diverifikasi_oleh',
            field=models.CharField(default='Diverifikasi oleh', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='expired_date',
            field=models.CharField(default='Expired Date', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='hasil_penimbangan',
            field=models.CharField(default='Hasil Penimbangan', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='nama',
            field=models.CharField(default='Nama', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='nama_produk',
            field=models.CharField(default='Nama Produk', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='no_batch',
            field=models.CharField(default='No Batch', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='no_karton',
            field=models.CharField(default='No Karton', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='paraf',
            field=models.CharField(default='Paraf', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='tanggal_paraf',
            field=models.CharField(default='Tanggal', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='tanggal_penimbangan',
            field=models.CharField(default='Tanggal Penimbangan', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='user_1',
            field=models.CharField(default='user 1', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='user_2',
            field=models.CharField(default='user 2', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='user_3',
            field=models.CharField(default='user 3', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='user_4',
            field=models.CharField(default='user 4', max_length=50),
        ),
    ]
