# Generated by Django 3.1.6 on 2022-09-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0050_auto_20220918_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminconfig',
            name='tanggal_paraf',
            field=models.CharField(default='Supervisor DS&S', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='user_1',
            field=models.CharField(default='Petugas Penimbangan', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='user_2',
            field=models.CharField(default='Petugas Gudang', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='user_3',
            field=models.CharField(default='Supervisor Produksi', max_length=50),
        ),
    ]
