# Generated by Django 3.2.3 on 2022-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0051_auto_20220918_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminconfig',
            old_name='department',
            new_name='pdf_department',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='dilakukan_oleh',
            new_name='pdf_dilakukan_oleh',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='diperiksa_oleh',
            new_name='pdf_diperiksa_oleh',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='diverifikasi_oleh',
            new_name='pdf_diverifikasi_oleh',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='expired_date',
            new_name='pdf_expired_date',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='hasil_penimbangan',
            new_name='pdf_hasil_penimbangan',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='nama',
            new_name='pdf_nama',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='nama_produk',
            new_name='pdf_nama_produk',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='no_batch',
            new_name='pdf_no_batch',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='no_karton',
            new_name='pdf_no_karton',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='paraf',
            new_name='pdf_paraf',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='reporttitle',
            new_name='pdf_reporttitle',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='tanggal_paraf',
            new_name='pdf_tanggal_paraf',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='tanggal_penimbangan',
            new_name='pdf_tanggal_penimbangan',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='user_1',
            new_name='pdf_user_1',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='user_2',
            new_name='pdf_user_2',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='user_3',
            new_name='pdf_user_3',
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='user_4',
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_dn',
            field=models.CharField(default='DN', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_eff_date',
            field=models.CharField(default='Eff. Date', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_form',
            field=models.CharField(default='FORM', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_rev_of_dn',
            field=models.CharField(default='Rev. of DN', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_user_4',
            field=models.CharField(default='Supervisor Gudang', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_will_be_reviewed',
            field=models.CharField(default='This document will be reviewed on', max_length=50),
        ),
    ]
