# Generated by Django 3.2.3 on 2022-09-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0052_auto_20220919_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_dn_value',
            field=models.CharField(blank=True, default='NOT ASSIGNED', max_length=20),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_eff_date_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_will_be_reviewed_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='signingdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
