# Generated by Django 3.2.3 on 2022-09-26 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0053_auto_20220919_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminconfig',
            name='pdf_eff_date_value',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='pdf_will_be_reviewed_value',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
