# Generated by Django 3.2.3 on 2022-10-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0056_reprintlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprintlist',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
