# Generated by Django 3.2.3 on 2022-10-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0057_reprintlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_dn_date',
            field=models.CharField(default='Date', max_length=50),
        ),
    ]
