# Generated by Django 3.1.6 on 2022-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0058_adminconfig_pdf_dn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='printedon',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
