# Generated by Django 3.1.6 on 2022-12-18 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0059_register_printedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchno', models.CharField(max_length=15)),
                ('boxno', models.IntegerField()),
                ('status', models.IntegerField(default=None, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(null=True)),
                ('operator', models.CharField(default=None, max_length=50, null=True)),
                ('petugasgudang', models.CharField(default=None, max_length=50, null=True)),
                ('printedon', models.DateTimeField(default=None, null=True)),
                ('action', models.CharField(max_length=15)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='createdby_rel_history', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainApp.product')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updatedby_rel_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
