# Generated by Django 3.1.6 on 2022-12-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0060_registerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_dn_rev',
            field=models.CharField(default='DN Rev', max_length=50),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_dn_rev_value',
            field=models.CharField(default='NOT ASSIGNED', max_length=20),
        ),
    ]
