# Generated by Django 3.1.6 on 2022-12-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0061_auto_20221218_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminconfig',
            old_name='pdf_dn_rev_value',
            new_name='pdf_rev_of_dn_value',
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='pdf_dn_rev',
        ),
    ]
