# Generated by Django 3.1.6 on 2024-01-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0063_reportconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='batchno',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
