# Generated by Django 3.1.6 on 2024-01-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0064_auto_20240124_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportconfig',
            name='batchno',
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.report'),
            preserve_default=False,
        ),
    ]
