# Generated by Django 3.1.6 on 2024-01-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0066_reportconfigtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='pdf_template_name',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AddField(
            model_name='reportconfigtemplate',
            name='pdf_template_name',
            field=models.CharField(default='No Name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reportconfigtemplate',
            name='pdf_dn_value',
            field=models.CharField(default='NOT ASSIGNED', max_length=20),
        ),
    ]
