# Generated by Django 3.1.6 on 2024-01-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0067_auto_20240125_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminconfig',
            name='pdf_template_name',
            field=models.CharField(max_length=50),
        ),
    ]
