# Generated by Django 3.1.6 on 2024-01-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0068_auto_20240125_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfigtemplate',
            name='pdf_template_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
