# Generated by Django 3.2.3 on 2022-06-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_alias', models.CharField(max_length=30, unique=True)),
                ('feature_name', models.CharField(max_length=50, unique=True)),
                ('allowed_groups', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.group')),
            ],
        ),
    ]
