# Generated by Django 3.2.3 on 2022-06-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('secureapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslist',
            name='allowed_groups',
        ),
        migrations.AddField(
            model_name='accesslist',
            name='allowed_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
