# Generated by Django 3.2.3 on 2022-06-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0002_auto_20220627_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslist',
            name='feature_name',
            field=models.CharField(max_length=50),
        ),
    ]
